### ISSUE TITLE
possibility to also use `fake_create_with_setfile` when update/delete resources

### ISSUE THREAD

**Issue by ozid** [jeremmfr/terraform-provider-junos#329]
Hello,

Is there a reason to not include the "edit" and "del" to the file created with "fake_create_with_setfile"

It could be useful in case of using terraform with refresh=false for fast processing of all commands at once.

Thanks

**Comment by jeremmfr** [comment]
The main goal of `fake_create_with_setfile` is to be able, with one commit, to ***create*** a set of resources that would have been pre-validated. For example, when configuring a new device with a set of regular resources. And then, the option can be disabled to return on normal way to launch Terraform and process resources cycle (CRUD), because this option may generate extra config (not managed by Terraform) on Junos device or/and conflicts/errors for resources in tfstate due to many tests that are skipped and missing commit validation.

Following this goal, integrating the same option on ***update*** resource had no interest and as for the ***create***, there are the same issues with possible inconsistencies in tfstate and extra config on the Junos device due to missing commit validation.

Integrating the same option on ***delete*** resource is worse because if there is an error when commit, the resource has disappeared from tfstate but is still present on the Junos device.

I can maybe integrate the same option for the ***update*** but I don't see the benefit compared to the risk of making inconsistencies in tfstate and extra config on the Junos device.

**Comment by ozid** [comment]
Hello,

First of thanks for your interest and time you take to our issues

Well i understand why this is such a risky way of operating but this could be also a good way to perform very fast action toward the firewall for exemple when you need to operate very fast action on a lot of resources in my case i operate over 10000 resources in a single workspace. 

In my scenario this is mostly for fast processing, we have try the fake setfile with a custom script that is executed at the end of the apply wich do the check on the firewall / the rollback and notice us in case all commands were not applied successfully 

Also, we have hard time playing with resources dependency on terraform, it's very difficult with "depends_on" when you have this number of ressources. The big advantage of the fake file is to let us commit at the very end all commands without worrying about the dependancy 

I understand the **update** and **delete** are risky in case commands were not applied correctly on the firewall and create inconsistency with state file, but we would like to try with post check script

As long as you are aware i think this could be a good alternative to play with

**Comment by jeremmfr** [comment]
Ok, maybe the risk can be acceptable in some cases.

I will take care of adding options to create same workaround and use same file when ***update*** or ***delete*** resources.

> The main problem i see is for ordering rules

I don't see a problem. While ***update*** the resource, the provider generates lines to `detete` all rules and add again all `set` lines in the desired order.

**Comment by ozid** [comment]
Thanks you !

**Comment by jeremmfr** [comment]
Can you leave the issue open until it's integrated ?
