### ISSUE TITLE
Feature request: add junos_interfaces_logical_present

### ISSUE THREAD

**Issue by lotusnoir** [jeremmfr/terraform-provider-junos#641]
Hello,

Im currently trying to get a dynamic list of all security zones associated with each of the vsrx i have. 
I saw that in the data ressources there is the junos_interfaces_physical_present that return all interfaces:
Is it possible to create the same one for the logical ones ?

Thanks in advance

**Comment by jeremmfr** [comment]
Hi 👋

Thank you for raising this issue. Considering logical interfaces are under each parent physical interface when reading interfaces, instead of adding a new data-source, adding the data to the existing `interfaces_physical_present` data-source is more desirable.

I will take care of adding this.
